name: Code Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build & test
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js v20
        uses: actions/setup-node@v2
        with:
          node-version: 20.8
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check
        run: npm run check

      - name: Test with coverage
        run: npm run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
